### ISSUE TITLE
Error retrieving port from Gluetun API

### ISSUE THREAD

**Issue by Powablocks** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#1]
Hello,
I'm trying to use this mod but it doesn't find the port from the API : 
+ echo '04/20/24 08:57:29 [GSP] - Error retrieving port from Gluetun API.'
+ SLEEP_TIME=10
+ '[' -z 58936 ']'
+ '[' 10 -ne 10 ']'
+ sleep 10
+ :
+ SLEEP_TIME=120
+ '[' -n '' ']'
+ get_ports
+ case ${1,,} in
+ QBT=true
+ GTN=true
+ '[' true ']'
++ curl --silent --fail --show-error --cookie-jar /tmp/cookies.txt --cookie /tmp/cookies.txt http://localhost:8081/api/v2/app/preferences
++ jq .listen_port
+ QBT_PORT=58936
+ '[' true ']'
++ curl --silent --fail --show-error http://localhost:8000/v1/openvpn/portforwarded
++ jq .port

I'm using mullvad as vpn provider. It is configured with WireGuard.
My docker compose config for the stack : 
`services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /docker_volumes/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=...
      - WIREGUARD_ADDRESSES=10.68.20.132/32
      - SERVER_HOSTNAMES=fr-par-wg-002,fr-par-wg-005
      # Timezone for accurate log times
      - TZ=Europe/Paris
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent    
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8081
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main
      - GSP_SLEEP=120
      - GSP_MINIMAL_LOGS=false
      - GSP_DEBUG=true
    volumes:
      - /docker_volumes/qbitorrent/config:/config
      - /mnt/usb/data/:/data
    restart: always`

As anyone had this issue and was able to resolved it ?

**Comment by t-anc** [comment]
Hi !
I Will take a look in the afternoon.

At first glance, i can see that you are using mullvad but the
"VPN_PORT_FORWARDING_PROVIDER=protonvpn". Is that a working setup ?

In gluetun's logs, are you able to see the currently forwarded port ?

Regards,
Tanc

**Comment by Powablocks** [comment]
Thank, I am setting the forwarding provider because mullvad is not possible at default so it ask for pia or proton.
Yes I can see it in gluetun : 
![image](https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod/assets/16413448/ea64ba0e-45dc-44c1-bdde-2f7e5c3ee140)

**Comment by Powablocks** [comment]
One thing I see in qbittorrent logs is that it contact gluetun on "http://localhost:8000/v1/openvpn/portforwarded" but as I'm using wireguard, is it possible the url is different ?
I will try to add the real ip, maybe localhost is not retreiving it

**Comment by Powablocks** [comment]
I just tried with proton vpn and it works, the problem is from the vpn port forwarding not working with mullvad i think. 

Thanks for the help :)

**Comment by t-anc** [comment]
No problem :)

To answer the question, the URL is the same for wireguard and openvpn. (see here : https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md )

I'll write a troubleshooting helper when I have some time.
