### ISSUE TITLE
Control Server no longer publicly accessible after GlueTUN release v3.40.

### ISSUE THREAD

**Issue by PingoLeon** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#10]
Hello !

First of all, thank you so much for your work on this mod, it is really useful and it is exactly what I was looking for. 

I ran into this in the logs of GlueTUN while monitoring : 
`WARN [http server] route GET /v1/openvpn/portforwarded is unprotected by default, please set up authentication following the documentation at https://github.com/qdm12/gluetun-wiki/setup/advanced/control-server.md#authentication since this will become no longer publicly accessible after release v3.40.`

I've checked gluetun's wiki talking about this : 
[Gluetun Wiki about Control Server](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md#:~:text=to%20take%20effect.-,Authentication%20methods,-none%3A%20no%20authentication)

Does it means I have to disable authentication on the control server  (auth = "none") or the mod includes the possibility to include username, password or API key in the HTTP Headers ? Do you plan to add this authentication later on ? I just need to have this information so that my configuration does not break randomly 😅

Thank you for your help, really

**Comment by t-anc** [comment]
Hi ! 
I'm aware of this change and of course I'm planning on integrating it to the mod. At the moment I really don't have time but I will integrate the ApiKey, and maybe username/password as soon as possible. It will also be possible to use docker secret to manage this (as of qbt password).
Since I don't really know how long it will take me (I'm moving and so my server is offline), you can set the route `/v1/openvpn/portforwarded` with auth=none at the moment and use the apikey after i'm done. This is the only route this mod uses.

I hope I'll be able to do that quickly,
Thank you for the heads up,
t-anc

**Comment by PingoLeon** [comment]
Thanks a lot for your quick answer 
No need to stress up, it can stay unauthentified for some time it won't be a big deal, since it was from the beginning 😅

I leave the .toml config here if anyone come up on this issue in the meantime : 
`[[roles]]
name = "qbittorrent GSP Docker Mod"
routes = ["GET /v1/openvpn/portforwarded"]
auth = "none"`

docker-compose.yml : 
```
gluetun:

    image: qmcgaw/gluetun:latest
    volumes:
      - /config/gluetun:/gluetun
      - /config/gluetun/config.toml:/gluetun/auth/config.toml:ro

```

Again, thank you for your work t-anc, it helps so much

**Comment by t-anc** [comment]
Re-opening to avoid duplicates, will close when the implemntation is done :)

**Comment by t-anc** [comment]
Should be done. Added `GSP_GTN_API_KEY` to the mod (and the doc). Tell me if you have any bug using it.

**Comment by PingoLeon** [comment]
I'll try this out in a couple of hours and tell you

**Comment by tikibozo** [comment]
Looks good to me - gluetun is no longer complaining about the api access, and the plugin is able to retrieve the port:

```
qbittorrent   | 09/22/24 22:08:47 [GSP] - Waiting for Qbittorrent WebUI ...
gluetun-qbt   | 2024-09-23T05:08:47Z INFO [vpn] You are running on the bleeding edge of latest!
gluetun-qbt   | 2024-09-23T05:08:47Z INFO [port forwarding] starting
gluetun-qbt   | 2024-09-23T05:08:47Z INFO [port forwarding] Found saved forwarded port data for port 56869
gluetun-qbt   | 2024-09-23T05:08:47Z INFO [port forwarding] Port forwarded data expires in 43 days
qbittorrent   | WebUI will be started shortly after internal preparations. Please wait...
qbittorrent   |
qbittorrent   | ******** Information ********
qbittorrent   | To control qBittorrent, access the WebUI at: http://localhost:8081
qbittorrent   |
gluetun-qbt   | 2024-09-23T05:08:47Z INFO [port forwarding] port forwarded is 56869
gluetun-qbt   | 2024-09-23T05:08:47Z INFO [firewall] setting allowed input port 56869 through interface tun0...
gluetun-qbt   | 2024-09-23T05:08:47Z INFO [port forwarding] writing port file /tmp/gluetun/forwarded_port
qbittorrent   | Connection to localhost (::1) 8081 port [tcp/tproxy] succeeded!
qbittorrent   | [ls.io-init] done.
gluetun-qbt   | 2024-09-23T05:08:53Z INFO [http server] 200 GET /portforwarded wrote 15B to [::1]:56748 in 33.668µs
qbittorrent   | 09/22/24 22:08:53 [GSP] - Init checks passed. Listening for a change.
gluetun-qbt   | 2024-09-23T05:08:53Z INFO [http server] 200 GET /portforwarded wrote 15B to [::1]:56760 in 22.504µs
```

Thank you!

**Comment by PingoLeon** [comment]
Can confirm what @tikibozo said, it works flawlessly !
Following the wiki is straightforward
GlueTUN logs :
```
2024-09-23T05:33:06Z INFO [http server] 200 GET /portforwarded wrote 15B to [::1]:36194 in 145.732µs
2024-09-23T05:33:06Z INFO [http server] 200 GET /portforwarded wrote 15B to [::1]:36206 in 54.457µs
```
Qbittorrent logs : 
```
09/23/24 07:33:06 [GSP] - Init checks passed. Listening for a change.
09/23/24 07:33:06 [GSP] - Ports changed :
09/23/24 07:33:06 [GSP] -  - Old : 65049
09/23/24 07:33:06 [GSP] -  - New : 64881
09/23/24 07:33:06 [GSP] - Updating qbittorrent port via API ...
09/23/24 07:33:06 [GSP] - Qbittorrent port successfully updated.
```

Merci beaucoup @t-anc 💯
