### ISSUE TITLE
Support for gluetun authentication to /v1/openvpn/portforwarded

### ISSUE THREAD

**Issue by tikibozo** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#11]
Looks like gluetun is locking down their routes. Do you have time to add support for this so the plugin will continue to work after gluetun v3.41.0?

More information on gluetun's wiki here:
https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md#authentication

Thanks!

**Comment by t-anc** [comment]
Hi,

Thanks for the feedback, yeah I'll add support for the auth as discussed on #10 :)

I'll reopen it and close this one to centralize everything, but thank you for the heads up,

t-anc
