### ISSUE TITLE
Feature request make this for plex as well plz

### ISSUE THREAD

**Issue by christianmerges** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#6]
Would it be possible to build the same for updating the port in plex, to make plex available via a separate glue-tun container? The port is set via the plex web interface, but I don't have the knowledge to reverse engineer this.

**Comment by t-anc** [comment]
Hi, I use Jellyfin and not plex, so I have no plan to do that (nor install plex to test it). 
As explained somewhere else, this mod is very simple and basically just call gluetun's API to retrieve the current port and qbt's API to set it. Without any check or logic, it could be done in 3 lines of code.
If someone wants to take inspiration from y mod to develop something for plex, go ahead ! 
While it would be possible to make a dedicated container for this, this mod was designed as a linuxserver's mod so to be consistant idealy you would need this image as your plex : https://docs.linuxserver.io/images/docker-plex/ 
I'll close this issue, but if someone feels like doing that, you can still post the link here.
