### ISSUE TITLE
Error retrieving port from Gluetun API when using Perfect Privacy as VPN (3 open ports)

### ISSUE THREAD

**Issue by Fantastandl** [t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#7]
Hi,
thanks for your mod, seems to be exactly what I need, but unfortunately I can't get it to work.
I already checked your troubleshooting section (which helped) but I think there's still a problem left, that I cannot solve:
Perfect Privacy generates 3 ports that are generated by the internal VPN-IP that changes with every new VPN connection.

For example, this is what I get from accessing the Gluetun API in my browser (http://192.168.188.15:8000/v1/openvpn/portforwarded):
`{"ports":[10550,20550,30550]}`

Does anybody know how to solve this?

**Comment by t-anc** [comment]
Hi ! 
Yeah, I've never had multiples ports, so it's not implemented yet and I'm currently moving so my server is offline.
I'll try to add this to the mod when I can. 
I have some question then : Are the ports always in the same order (seems like they are sorted from smaller to bigger) ?
How do you chose which port you'll use ? If i implement a variable that allows you to use the X's port (so 1, 2 or 3 in your case), is that alright for your use case ? 

Thank you,

**Comment by t-anc** [comment]
I try to keep things as much configurable as possible, but also very "plug and play". So I'll probably add a variable to tune this, and set it as default = 1.
However I don't have much time at the moment, so I'll probably work on it on the last week of september. Sorry for the delay  :/ ...

In the meantime, if someone else that needs multiple ports comes here and have a suggestion, don't hesitates :)

**Comment by t-anc** [comment]
Hi ! It should be ok, without any config it will use the first port, but you can use the variable `GSP_PORT_INDEX` to use another one.
Don't hesitate if you have feedbacks or bugs :)

**Comment by Fantastandl** [comment]
Hey,
thanks for your help.
Although I couldn't get it to run yet xD But I think that has nothing to do with your code, more like with the API change of gluetun...
Do you happen to know, if I need to bind the config.toml directly or if I can  just drop it in a mounted volume?

**Comment by t-anc** [comment]
Hi, I just recently updated the README and the compose example to take into account changes in Gluetun's API. You can take a look at the doc and open another issue if you think I can improve it :)

**Comment by olvier** [comment]
Maybe try again? :)

#12 >> https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod/issues/12#issuecomment-2400314528


The are also some changes in gluetun, why i'm using v.3.39.0
v3.39.1: "Control server: require authentication for vulnerable routes (https://github.com/qdm12/gluetun/pull/2434)"
```
 gluetun:
     image: qmcgaw/gluetun:v3.39.0
```

and also last version before qbittorrent 5.x.x.
Dont know, whether there are breaking changes or not.
```
 qbittorrent:
   # image: ghcr.io/linuxserver/qbittorrent          # orig
     image: linuxserver/qbittorrent:4.6.7
```

Will test both `:latest` in future.

**Comment by t-anc** [comment]
I'm running in both `latest` without any issue, I just had to configure the `config.toml`.
You can follow the doc I wrote in the README and tell me if something needs clarification.
@Fantastandl  I fixed some issues linked to multiple ports, you can re-try now and let me know if it works for you.

**Comment by Fantastandl** [comment]
Just updated both containers to their latest versions and it works.

Before he tried to fill the new port with a null value. But I could not work out whether it was because something gluetun did or because of your mod. I didn't change anything in addition to those updates.

Again, thank you very much for your mod and help :)

**Comment by t-anc** [comment]
Oh nice. Yeah as discussed in #12, it was a mistake in the mod, not your config.
If everything works for you, I'll let you close the issue :) 
Bye
